### ISSUE TITLE
师傅你好，可以向你讨教一下，部署这个扫描仪出现的一些问题吗！

### ISSUE THREAD

**Issue by MrShiF** [b0bac/ApolloScanner#10]
师傅你好，可以向你讨教一下，部署这个扫描仪出现的一些问题吗！

**Comment by b0bac** [comment]
可以直接贴问题

**Comment by MrShiF** [comment]
![bc056c7232cf35a193410a1ec5586b3](https://user-images.githubusercontent.com/90505986/159885400-1055452c-c804-46b7-92f5-9cd70a3413e6.png)

**Comment by MrShiF** [comment]
一言难尽，部署不太顺利

**Comment by MrShiF** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.db.backends.mysql'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 300, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>

**Comment by b0bac** [comment]
目测是没有模块，你的django版本是？

**Comment by b0bac** [comment]
建议查看一下依赖库是否安装

**Comment by MrShiF** [comment]
django 4.0.1   依赖库 直接执行pip  -m install re.......txt 前面出了点错，后面解决了正常全安装完成了

**Comment by b0bac** [comment]
pip安装默认安装到python2 需要执行python3 -m pip install -r ...如果使用所有功能，建议sudo启动，那么应该执行sudo  python3 -m pip install -r ...

**Comment by MrShiF** [comment]
我试试，谢谢师傅

**Comment by MrShiF** [comment]
我思来想去，不是这个问题，真实奇怪了

**Comment by b0bac** [comment]
可以直接python3 -m pip list 查看
