### ISSUE TITLE
kali 报错能看下吗

### ISSUE THREAD

**Issue by zs198945** [b0bac/ApolloScanner#4]
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /bin/sh: 1: mysql_config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a97fgjbo/mysqlclient_f2403b13f7fe41259413094ec5354b47/setup.py", line 16, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-a97fgjbo/mysqlclient_f2403b13f7fe41259413094ec5354b47/setup_posix.py", line 51, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-a97fgjbo/mysqlclient_f2403b13f7fe41259413094ec5354b47/setup_posix.py", line 29, in mysql_config
          raise EnvironmentError("%s not found" % (_mysql_config_path,))
      OSError: mysql_config not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by b0bac** [comment]
与ubuntu和macos环境类似，请Google安装或软连接mysql_config
